package org.lby.s12368.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-20T15:58:27.168+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://webservice.server.webservice.qmhd.com.cn", name = "SMSPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SMSPortType {

    @WebMethod(action = "urn:mtSmsList")
    @Action(input = "urn:mtSmsList", output = "urn:mtSmsListResponse")
    @RequestWrapper(localName = "mtSmsList", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn", className = "org.lby.s12368.client.MtSmsList")
    @ResponseWrapper(localName = "mtSmsListResponse", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn", className = "org.lby.s12368.client.MtSmsListResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
    public java.lang.String mtSmsList(
        @WebParam(name = "loginID", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String loginID,
        @WebParam(name = "passWord", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String passWord,
        @WebParam(name = "strXml", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String strXml
    );

    @WebMethod(action = "urn:updatePassWord")
    @Action(input = "urn:updatePassWord", output = "urn:updatePassWordResponse")
    @RequestWrapper(localName = "updatePassWord", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn", className = "org.lby.s12368.client.UpdatePassWord")
    @ResponseWrapper(localName = "updatePassWordResponse", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn", className = "org.lby.s12368.client.UpdatePassWordResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
    public java.lang.String updatePassWord(
        @WebParam(name = "loginID", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String loginID,
        @WebParam(name = "oldPassWord", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String oldPassWord,
        @WebParam(name = "newPassWord", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String newPassWord
    );

    @WebMethod(action = "urn:statisticsSmsList")
    @Action(input = "urn:statisticsSmsList", output = "urn:statisticsSmsListResponse")
    @RequestWrapper(localName = "statisticsSmsList", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn", className = "org.lby.s12368.client.StatisticsSmsList")
    @ResponseWrapper(localName = "statisticsSmsListResponse", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn", className = "org.lby.s12368.client.StatisticsSmsListResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
    public java.lang.String statisticsSmsList(
        @WebParam(name = "loginID", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String loginID,
        @WebParam(name = "passWord", targetNamespace = "http://webservice.server.webservice.qmhd.com.cn")
        java.lang.String passWord
    );
}
