
package org.lby.s12368.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-20T15:58:27.179+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class SMSPortType_SMSHttpEndpoint_Server{

    protected SMSPortType_SMSHttpEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SMSHttpEndpointImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SMSPortType_SMSHttpEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
