
package org.lby.s12368.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-20T15:58:27.192+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class SMSPortType_SMSHttpSoap12Endpoint_Server{

    protected SMSPortType_SMSHttpSoap12Endpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SMSHttpSoap12EndpointImpl();
        String address = "http://192.2.102.157/services/SMS.SMSHttpSoap12Endpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SMSPortType_SMSHttpSoap12Endpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
