
package org.lby.s12368.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-20T15:58:27.103+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class SMSPortType_SMSHttpSoap11Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.server.webservice.qmhd.com.cn", "SMS");

    private SMSPortType_SMSHttpSoap11Endpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SMS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SMS ss = new SMS(wsdlURL, SERVICE_NAME);
        SMSPortType port = ss.getSMSHttpSoap11Endpoint();  
        
        {
        System.out.println("Invoking mtSmsList...");
        java.lang.String _mtSmsList_loginID = "";
        java.lang.String _mtSmsList_passWord = "";
        java.lang.String _mtSmsList_strXml = "";
        java.lang.String _mtSmsList__return = port.mtSmsList(_mtSmsList_loginID, _mtSmsList_passWord, _mtSmsList_strXml);
        System.out.println("mtSmsList.result=" + _mtSmsList__return);


        }
        {
        System.out.println("Invoking updatePassWord...");
        java.lang.String _updatePassWord_loginID = "";
        java.lang.String _updatePassWord_oldPassWord = "";
        java.lang.String _updatePassWord_newPassWord = "";
        java.lang.String _updatePassWord__return = port.updatePassWord(_updatePassWord_loginID, _updatePassWord_oldPassWord, _updatePassWord_newPassWord);
        System.out.println("updatePassWord.result=" + _updatePassWord__return);


        }
        {
        System.out.println("Invoking statisticsSmsList...");
        java.lang.String _statisticsSmsList_loginID = "";
        java.lang.String _statisticsSmsList_passWord = "";
        java.lang.String _statisticsSmsList__return = port.statisticsSmsList(_statisticsSmsList_loginID, _statisticsSmsList_passWord);
        System.out.println("statisticsSmsList.result=" + _statisticsSmsList__return);


        }

        System.exit(0);
    }

}
