package org.lby.kq.model;

import org.lby.kq.model.base.BaseApply;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Apply extends BaseApply<Apply> {
    public static final Apply dao = new Apply();

    public List<Apply> find_sq(String email) {
        return find("select * from " + TABLENAME + " where sqr=?", email);
    }

    public List<Apply> find_db(String email) {
        return find("select * from " + TABLENAME + " where spr=?", email);
    }
}
