package org.lby.kq.model;

import org.lby.kq.model.base.BaseApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Apply extends BaseApply<Apply> {
	public static final Apply dao = new Apply();
}
