package org.lby.kq.model;

import com.jfinal.plugin.activerecord.Db;
import org.lby.kq.model.base.BaseBridgeConfigUnit;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BridgeConfigUnit extends BaseBridgeConfigUnit<BridgeConfigUnit> {
    public static final BridgeConfigUnit dao = new BridgeConfigUnit();

    public void clean_by_config(ConfigTime configTime) {
        Db.update("delete from " + TABLENAME + " where confId=?", configTime.getId());
    }

    public BridgeConfigUnit find_by_config(ConfigTime configTime) {
        return findFirst("select * from " + TABLENAME + " where confId=?", configTime.getId());
    }

    public String find_conId(Object unit, Long unitType) {
        return Db.queryStr("select confId from " + TABLENAME + " where unit=? and unitType=? limit 1", unit, unitType);
    }

    public Long count_by_unit_unitType(Object unit, Object unitType) {
        return Db.queryLong("select count(0) from " + TABLENAME + " where unit=? and unitType=? ", unit, unitType);
    }
}