package org.lby.kq.model;

import com.jfinal.plugin.activerecord.Db;
import org.lby.kq.model.base.BaseBridgeConfigUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BridgeConfigUnit extends BaseBridgeConfigUnit<BridgeConfigUnit> {
    public static final BridgeConfigUnit dao = new BridgeConfigUnit();

    public void clean_by_config(ConfigTime configTime) {
        Db.update("delete from " + TABLENAME + " where confId=?", configTime.getId());
    }
}