package org.lby.kq.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import org.lby.kq.model.base.BaseConfigTime;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfigTime extends BaseConfigTime<ConfigTime> {
    public static final ConfigTime dao = new ConfigTime();

    /**
     * @param email
     */
    public List<Record> find_by_email(String email) {
        return Db.find("select * from " + TABLENAME + " where provider=? order by createTime desc", email);
    }
}
