package org.lby.kq.model;

import org.lby.kq.model.base.BaseConfigTime;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfigTime extends BaseConfigTime<ConfigTime> {
    public static final ConfigTime dao = new ConfigTime();

    /**
     * @param email
     */
    public List<ConfigTime> find_by_email(String email) {
        return find("select * from " + TABLENAME + " where provider=?", email);
    }
}
