package org.lby.kq.model;

import com.jfinal.plugin.activerecord.Db;
import org.lby.kq.model.base.BaseSalary;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salary extends BaseSalary<Salary> {
    public static final Salary dao = new Salary();


    public boolean isCanDK(String email, Integer type) {
        Long c = Db.queryLong("select count(0) from " + TABLENAME + " where yx=? and type=? and date(now())=date(time_dj)", email, type);
        return c == 0;
    }

    /**
     * 查找当天的打卡记录
     *
     * @return
     */
    public List<Salary> find_email_now(String email) {
        return find("select * from " + TABLENAME + " where yx=? and date(time_dj)=date(now())",email);
    }
}
