package org.lby.kq.model;

import org.lby.kq.model.base.BaseSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salary extends BaseSalary<Salary> {
	public static final Salary dao = new Salary();
}
