package org.lby.kq.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 邹宇泉, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfigTime<M extends BaseConfigTime<M>> extends Model<M> implements IBean {

	public static String TABLENAME="kq_config_time";
	public M setId(java.lang.String id) {
		set("id", id);
	return (M)this;
}

	public java.lang.String getId() {
		return get("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
	return (M)this;
}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setVcTime(java.lang.String vcTime) {
		set("vcTime", vcTime);
	return (M)this;
}

	public java.lang.String getVcTime() {
		return get("vcTime");
	}

}
