package org.lby.kq.model.common.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 邹宇泉, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public static String TABLENAME="qxgl_role";
	public M setId(java.lang.Integer id) {
		set("id", id);
	return (M)this;
}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setRole(java.lang.Integer role) {
		set("role", role);
	return (M)this;
}

	public java.lang.Integer getRole() {
		return get("role");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
	return (M)this;
}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setType(java.lang.String type) {
		set("type", type);
	return (M)this;
}

	public java.lang.String getType() {
		return get("type");
	}

	public M setRoleType(java.lang.Integer roleType) {
		set("roleType", roleType);
	return (M)this;
}

	public java.lang.Integer getRoleType() {
		return get("roleType");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
	return (M)this;
}

	public java.util.Date getCtime() {
		return get("ctime");
	}

}
