package org.lby.kq.model.common.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 邹宇泉, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermi<M extends BaseRolePermi<M>> extends Model<M> implements IBean {

	public static String TABLENAME="qxgl_role_permi";
	public M setId(java.lang.Integer id) {
		set("id", id);
	return (M)this;
}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setRole(java.lang.Integer role) {
		set("role", role);
	return (M)this;
}

	public java.lang.Integer getRole() {
		return get("role");
	}

	public M setPermi(java.lang.Integer permi) {
		set("permi", permi);
	return (M)this;
}

	public java.lang.Integer getPermi() {
		return get("permi");
	}

	public M setType(java.lang.String type) {
		set("type", type);
	return (M)this;
}

	public java.lang.String getType() {
		return get("type");
	}

}
