package org.lby.kq.model.common.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 邹宇泉, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleScope<M extends BaseRoleScope<M>> extends Model<M> implements IBean {

	public static String TABLENAME="qxgl_role_scope";
	public M setId(java.lang.Integer id) {
		set("id", id);
	return (M)this;
}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setRole(java.lang.Integer role) {
		set("role", role);
	return (M)this;
}

	public java.lang.Integer getRole() {
		return get("role");
	}

	public M setScope(java.lang.Integer scope) {
		set("scope", scope);
	return (M)this;
}

	public java.lang.Integer getScope() {
		return get("scope");
	}

	public M setType(java.lang.String type) {
		set("type", type);
	return (M)this;
}

	public java.lang.String getType() {
		return get("type");
	}

}
