package org.lby.kq.model.common.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 邹宇泉, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScope<M extends BaseScope<M>> extends Model<M> implements IBean {

	public static String TABLENAME="qxgl_scope";
	public M setId(java.lang.Integer id) {
		set("id", id);
	return (M)this;
}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setVal(java.lang.Integer val) {
		set("val", val);
	return (M)this;
}

	public java.lang.Integer getVal() {
		return get("val");
	}

	public M setDeptId(java.lang.Integer deptId) {
		set("deptId", deptId);
	return (M)this;
}

	public java.lang.Integer getDeptId() {
		return get("deptId");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
	return (M)this;
}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setType(java.lang.String type) {
		set("type", type);
	return (M)this;
}

	public java.lang.String getType() {
		return get("type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	return (M)this;
}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
