package com.zyq.quick_monitor.view.mstsc;

import com.jfinal.ext.zyq.plugin.MongoKit;
import com.mongodb.BasicDBObject;
import com.zyq.quick_monitor.entity.Mstsc;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Administrator on 2016/6/24.
 */
public class Add {
    private JPanel p;
    private JLabel p1;
    private JTextField t1;
    private JLabel p3;
    private JLabel p2;
    private JButton b1;
    private JTextField t2;
    private JTextField t3;

    public Add() {
        b1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                MongoKit.getCollection("mstsc").insert(new BasicDBObject());
                new Mstsc().setAddress(t1.getText()).setUsername(t2.getText()).setPass(t3.getText()).save();
            }
        });

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        p = new JPanel();
        p.setLayout(new GridBagLayout());
        p1 = new JLabel();
        p1.setText("服务器地址：");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        p.add(p1, gbc);
        t1 = new JTextField();
        t1.setPreferredSize(new Dimension(200, 20));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        p.add(t1, gbc);
        t2 = new JTextField();
        t2.setPreferredSize(new Dimension(200, 20));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        p.add(t2, gbc);
        t3 = new JTextField();
        t3.setPreferredSize(new Dimension(200, 20));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        p.add(t3, gbc);
        p2 = new JLabel();
        p2.setText("用户名：");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        p.add(p2, gbc);
        p3 = new JLabel();
        p3.setText("密码：");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        p.add(p3, gbc);
        b1 = new JButton();
        b1.setText("确定");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        p.add(b1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return p;
    }
}
