package org.lby.kq.model.common;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("qxgl_admin", "id", Admin.class);
		arp.addMapping("qxgl_permi", "id", Permi.class);
		arp.addMapping("qxgl_role", "id", Role.class);
		arp.addMapping("qxgl_role_permi", "id", RolePermi.class);
		arp.addMapping("qxgl_role_scope", "id", RoleScope.class);
		arp.addMapping("qxgl_scope", "id", Scope.class);
	}
}

