package org.lby.kq.model.common;

import org.lby.kq.model.common.base.BasePermi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permi extends BasePermi<Permi> {
	public static final Permi dao = new Permi();
}
