package org.lby.kq.model.common;

import org.lby.kq.model.common.base.BaseRoleScope;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleScope extends BaseRoleScope<RoleScope> {
	public static final RoleScope dao = new RoleScope();
}
