package org.lby.kq.model.common;

import org.lby.kq.model.common.base.BaseRolePermi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermi extends BaseRolePermi<RolePermi> {
	public static final RolePermi dao = new RolePermi();
}
