package org.lby.kq.model.common;

import org.lby.kq.model.common.base.BaseScope;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scope extends BaseScope<Scope> {
	public static final Scope dao = new Scope();
}
